### ISSUE TITLE
A severe problem occurred during the spawning of an entity at (coords)

### ISSUE THREAD

**Issue by katubug** [FrenchUranoscopidae/Hated_Mobs#21]
Link to error: https://paste.dimdev.org/ufewihumuz.mccrash
All mods with versions are listed in the crash.

Basically, it seems my game is having an issue with mobs from your mod trying to spawn. This is definitely a mod conflict, because in an isolated instance, it doesn't occur. It seems to be with Food Funk's library mod, Wumple Util. However, I don't have time right now to test it out, my apologies. Please do let me know if I can provide you any more information, and I'll get it as soon as I have access to my PC again.

Thanks for your time!

**Comment by FrenchUranoscopidae** [comment]
Hello ! Thanks for reporting this issue, it looks like the way my mod handles silk spiders and mosquitoes is at fault (They need to be able to gro through specific blocks and the way Minecraft is programmed makes it MUCH harder than it sounds :/ ) I will try to see what I can do to fix this, but the fix probably won't be here before a while.

**Comment by katubug** [comment]
Understandable! Take your time :D Thanks very much for your response, and please let me know if I can help in any way. :)

**Comment by SandwichHorror** [comment]
Also got this error with the latest update for both WumpleUtil and Totem Expansion. Hope to see this fixed!

**Comment by FrenchUranoscopidae** [comment]
I'll try my best but truth is I had a lot of issues like this since the beginning and they keep popping up ! I'm still trying to figure out a way to definitely end those problems. Even though I'm not planning any more content for 1.12.2, if I find a fix, I'll make a 1.12.2 update for it

**Comment by MechanosG** [comment]
Heya.  Same problem here.  In my case, there seems to be a conflict between Hated Mobs and Electrobob's Wizardry.  No rush though, just reporting this in case it helps.

[crash-2020-02-18_12.28.34-client.txt](https://github.com/FrenchUranoscopidae/Hated_Mobs/files/4221568/crash-2020-02-18_12.28.34-client.txt)

Out of curiosity, if this is due to certain mobs wanting to pass through certain blocks..  could a workaround be done, such as..  instead of changing or relying on certain blocks (I assume this is what's causing errors between mods somehow), instead have the mob check for air blocks on the other side of the glass/door/leaves and teleport it's way through by setting it's position to inside the glass/door/leaves, then after a moment setting it's position to the air block on the other side?

**Comment by FrenchUranoscopidae** [comment]
The problem is more about the pathfinding system rather than the mob going through the block in itself, and thanks for the crashlog, I'll check it out too !

**Comment by axalox** [comment]
Hello

Same problem, since i've installed your mod , i get a lot of errors message and crash reports

Hated Mobs 1.5.0 (1.12.2)

![image](https://user-images.githubusercontent.com/32990916/119323203-bd22ae80-bc7e-11eb-9ab3-6aafec1af4b1.png)


one crash report

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2021-05-24 10:34:01 CEST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.RuntimeException: A severe problem occurred during the spawning of an entity at (934.5, 62.0, 698.5)
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: A severe problem occurred during the spawning of an entity at (934.5, 62.0, 698.5)
    at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:135)
    at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.process(EntitySpawnHandler.java:64)
    at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.lambda$channelRead0$0(EntitySpawnHandler.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 17 more
Caused by: java.lang.NullPointerException
    at fr.uranoscopidae.hatedmobs.common.worldwrappers.FalsifiedWorldClient.getTotalWorldTime(FalsifiedWorldClient.java:1057)
    at com.wumple.util.misc.TimeUtil.setTimestamp(TimeUtil.java:55)
    at com.wumple.util.misc.TimeUtil.onWorldLoad(TimeUtil.java:101)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_186_TimeUtil_onWorldLoad_Load.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.call(Reflector.java:976)
    at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
    at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:98)
    at fr.uranoscopidae.hatedmobs.common.worldwrappers.FalsifiedWorldClient.<init>(FalsifiedWorldClient.java:57)
    at fr.uranoscopidae.hatedmobs.common.worldwrappers.IBlockMapper.attemptWrapClient(IBlockMapper.java:58)
    at fr.uranoscopidae.hatedmobs.common.worldwrappers.IBlockMapper.wrapDirect(IBlockMapper.java:49)
    at fr.uranoscopidae.hatedmobs.common.worldwrappers.IBlockMapper.wrap(IBlockMapper.java:22)
    at fr.uranoscopidae.hatedmobs.common.entities.EntityMosquito.<init>(EntityMosquito.java:27)
    at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.newInstance(EntityRegistry.java:99)
    at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:87)
    ... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_291, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1335984896 bytes (1274 MB) / 3288334336 bytes (3136 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 127 mods loaded, 127 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version              | Source                                                | Signature                                |
       |:------ |:-------------------- |:-------------------- |:----------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2               | minecraft.jar                                         | None                                     |
       | LCHIJA | mcp                  | 9.42                 | minecraft.jar                                         | None                                     |
       | LCHIJA | FML                  | 8.0.99.99            | forge-1.12.2-14.23.5.2855-universal.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2855         | forge-1.12.2-14.23.5.2855-universal.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy    | 1.0.0                | minecraft.jar                                         | None                                     |
       | LCHIJA | otgcore              | 1.12.2-v9.3          | minecraft.jar                                         | None                                     |
       | LCHIJA | xaerominimap_core    | 1.12.2-1.0           | minecraft.jar                                         | None                                     |
       | LCHIJA | xaeroworldmap_core   | 1.12.2-1.0           | minecraft.jar                                         | None                                     |
       | LCHIJA | bnbgamingcore        | 0.11.0               | minecraft.jar                                         | None                                     |
       | LCHIJA | tickcentral          | 3.2                  | TickCentral-3.2.jar                                   | None                                     |
       | LCHIJA | passableleavescore   | 1.0.0                | minecraft.jar                                         | None                                     |
       | LCHIJA | randompatches        | 1.12.2-1.22.1.10     | randompatches-1.12.2-1.22.1.10.jar                    | None                                     |
       | LCHIJA | abyssaldepths        | 1.12.2-0.3.1         | AbyssalDepths-1.12.2-0.3.1.jar                        | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCHIJA | creativecore         | 1.10.0               | CreativeCore_v1.10.57_mc1.12.2.jar                    | None                                     |
       | LCHIJA | ambientsounds        | 3.0                  | AmbientSounds_v3.1.5_mc1.12.2.jar                     | None                                     |
       | LCHIJA | craftstudioapi       | 1.0.0                | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar    | None                                     |
       | LCHIJA | wildlands_alpha      | 0.1                  | Wildlands-1.12.2-alpha-0.1.jar                        | None                                     |
       | LCHIJA | openterraingenerator | v9.3                 | OpenTerrainGenerator-1.12.2-v9.3.jar                  | None                                     |
       | LCHIJA | harvestcraft         | 1.12.2zb             | Pam's+HarvestCraft+1.12.2zg.jar                       | None                                     |
       | LCHIJA | animania             | 2.0.3.28             | animania-1.12.2-base-2.0.3.28.jar                     | None                                     |
       | LCHIJA | baubles              | 1.5.2                | Baubles-1.12-1.5.2.jar                                | None                                     |
       | LCHIJA | artifacts            | 1.12.2-1.2.3         | Artifacts-1.12.2-1.2.3.jar                            | None                                     |
       | LCHIJA | autoplant            | 1.12-1.0.0           | autoplant-1.12-1.0.0.jar                              | None                                     |
       | LCHIJA | jei                  | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                             | None                                     |
       | LCHIJA | quark                | r1.6-179             | Quark-r1.6-179.jar                                    | None                                     |
       | LCHIJA | autoreglib           | 1.3-32               | AutoRegLib-1.3-32.jar                                 | None                                     |
       | LCHIJA | ichunutil            | 7.2.2                | iChunUtil-1.12.2-7.2.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backtools            | 7.0.1                | BackTools-1.12.2-7.0.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | badmobs              | 1.1.40               | BadMobs-1.12.2-1.1.40.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | crafttweaker         | 4.1.20               | CraftTweaker2-1.12-4.1.20.618.jar                     | None                                     |
       | LCHIJA | base                 | 3.13.0               | base-1.12.2-3.13.0.jar                                | None                                     |
       | LCHIJA | coordinatesplusmod   | 1.12.0_004           | Batty's+Coordinates+PLUS+Mod+for+Forge-1.12.0_004.jar | None                                     |
       | LCHIJA | betteradvancements   | 0.1.0.77             | BetterAdvancements-1.12.2-0.1.0.77.jar                | None                                     |
       | LCHIJA | bettercaves          | 1.12.2               | bettercaves-1.12.2-2.0.4.jar                          | None                                     |
       | LCHIJA | forgelin             | 1.8.4                | Forgelin-1.8.4.jar                                    | None                                     |
       | LCHIJA | betterfoliage        | 2.3.1                | BetterFoliage-MC1.12-2.3.1.jar                        | None                                     |
       | LCHIJA | bettermineshafts     | 1.12.2-2.2.1         | BetterMineshaftsForge-1.12.2-2.2.1.jar                | None                                     |
       | LCHIJA | betterpingdisplay    | 1.0                  | BetterPingDisplay-1.12.2-1.0.jar                      | None                                     |
       | LCHIJA | betterwithmods       | 1.12-2.3.24          | BetterWithMods-1.12-2.3.24.jar                        | None                                     |
       | LCHIJA | biomebundle          | 5.1                  | Biome_Bundle-1.12.2-v6.1.jar                          | None                                     |
       | LCHIJA | bloodmoon            | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | bnbgaminglib         | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                        | None                                     |
       | LCHIJA | butterflies          | 1.12.2-1.0.3         | butterflies-1.12.2-1.0.3.jar                          | None                                     |
       | LCHIJA | carryon              | 1.12.3               | carryon-1.12.2-1.12.4.16.jar                          | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCHIJA | chunkanimator        | 1.2                  | ChunkAnimator-MC1.12-1.2.jar                          | None                                     |
       | LCHIJA | collective           | 2.26                 | collective-1.12.2-2.26.jar                            | None                                     |
       | LCHIJA | morpheus             | 1.12.2-3.5.106       | Morpheus-1.12.2-3.5.106.jar                           | None                                     |
       | LCHIJA | comforts             | 1.4.1.3              | comforts-1.12.2-1.4.1.3.jar                           | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | contenttweaker       | 1.12.2-4.9.1         | ContentTweaker-1.12.2-4.9.1.jar                       | None                                     |
       | LCHIJA | coralreef            | 2.0                  | CoralReef-2.5-1.12.2.jar                              | None                                     |
       | LCHIJA | ctgui                | 1.0.0                | CraftTweaker2-1.12-4.1.20.618.jar                     | None                                     |
       | LCHIJA | crafttweakerjei      | 2.0.3                | CraftTweaker2-1.12-4.1.20.618.jar                     | None                                     |
       | LCHIJA | defaultoptions       | 9.2.8                | DefaultOptions_1.12.2-9.2.8.jar                       | None                                     |
       | LCHIJA | dregora              | 1.0                  | Dregora-1.12.2-v1.66.2.jar                            | None                                     |
       | LCHIJA | dynamictrees         | 1.12.2-0.9.23        | DynamicTrees-1.12.2-0.9.23.jar                        | None                                     |
       | LCHIJA | emojicord            | 1.1.1.39             | Emojicord-1.12.2-1.1.1.39-universal.jar               | None                                     |
       | LCHIJA | epicfight            | 1.12.2-2.0.0         | EpicFightMod-1.12.2-2.2.0.jar                         | None                                     |
       | LCHIJA | exoticbirds          | 1.0                  | Exotic Birds 1.12.2-3.2.0.jar                         | None                                     |
       | LCHIJA | familiarfauna        | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar                       | None                                     |
       | LCHIJA | farseek              | 2.5.1                | Farseek-1.12-2.5.1.jar                                | None                                     |
       | LCHIJA | ferdinandsflowers    | 1.10.4.1             | Ferdinand's Flowers-1.12.x-1.10.4.1.jar               | None                                     |
       | LCHIJA | wumpleutil           | 2.12.9               | wumpleutil-1.12.2-2.12.9.jar                          | None                                     |
       | LCHIJA | flourishingfoliage   | 1.0.2                | flourishingfoliage-1.12.2-1.0.2.jar                   | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCHIJA | forestry             | 5.8.2.387            | forestry_1.12.2-5.8.2.387.jar                         | None                                     |
       | LCHIJA | iceologer            | 1.5                  | Frozen-Fiend-1.5.jar                                  | None                                     |
       | LCHIJA | futuremc             | 0.2.6                | future-mc-1.12.2-0.2.6.1.jar                          | None                                     |
       | LCHIJA | futureminecraf       | 1.3.1                | FutureVersions+v1.3.1.jar                             | None                                     |
       | LCHIJA | goatmod              | 1.1                  | GoatMod-1.1.jar                                       | None                                     |
       | LCHIJA | happytrails          | 1.0.0.5              | HappyTrails-1.12.2-1.0.0.5.jar                        | None                                     |
       | LCHIJA | llibrary             | 1.7.20               | llibrary-1.7.20-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | hatedmobs            | 1.5.0                | hatedmobs-1.5.0.jar                                   | None                                     |
       | LCHIJA | waila                | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
       | LCHIJA | iblis_headshots      | 1.2.6                | iblis-headshots-1.2.6.jar                             | None                                     |
       | LCHIJA | ido                  | 1.0.6                | ido-1.12.2-1.1.0.jar                                  | None                                     |
       | LCHIJA | jaff                 | 1.7_for_1.12         | JustAFewFish-1.7_for_1.12.jar                         | None                                     |
       | LCHIJA | jeid                 | 1.0.3-55             | JustEnoughIDs-1.0.3-55.jar                            | None                                     |
       | LCHIJA | laggoggles           | 1.12.2-5.8-132       | LagGoggles-1.12.2-5.8-132.jar                         | None                                     |
       | LCHIJA | libraryex            | 1.2.1                | LibraryEx-1.12.2-1.2.1.jar                            | None                                     |
       | LCHIJA | testdummy            | 1.12                 | MmmMmmMmmMmm-1.12-1.14.jar                            | None                                     |
       | LCHIJA | mobcontroller        | 1.1                  | MobController-1.12.2-1.1.jar                          | None                                     |
       | LCHIJA | mowziesmobs          | 1.5.8                | mowziesmobs-1.5.8.jar                                 | None                                     |
       | LCHIJA | multimob             | 1.0.5                | multimob-1.0.5.jar                                    | None                                     |
       | LCHIJA | mutantbeasts         | 1.12.2-1.0.2         | MutantBeasts-1.12.2-1.0.2.jar                         | None                                     |
       | LCHIJA | roots                | 1.12.2-3.0.32        | Roots-1.12.2-3.0.32.jar                               | None                                     |
       | LCHIJA | mysticalworld        | 1.12.2-1.9.2         | mysticalworld-1.12.2-1.9.2.jar                        | None                                     |
       | LCHIJA | naturescompass       | 1.8.5                | NaturesCompass-1.12.2-1.8.5.jar                       | None                                     |
       | LCHIJA | netherex             | 2.2.4                | NetherEx-1.12.2-2.2.4.jar                             | None                                     |
       | LCHIJA | samsocean            | 1.0.2                | OceanFloor-1.12.2-1.0.2.jar                           | None                                     |
       | LCHIJA | paraglider           | 1.0.1.5              | Paraglider-1.12.2-1.0.1.5.jar                         | None                                     |
       | LCHIJA | patchouli            | 1.0-23.6             | Patchouli-1.0-23.6.jar                                | None                                     |
       | LCHIJA | pathundergates       | 1.12.2-2.2.0-release | pathundergates-1.12.2-2.2.0-release.jar               | None                                     |
       | LCHIJA | performant           | 1.12.2-1.4           | performant-1.12.2-1.10.jar                            | None                                     |
       | LCHIJA | pickupnotifier       | 1.1.5                | PickUpNotifier-v1.1.5-1.12.2.jar                      | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHIJA | primitivemobs        | 1.2.3a               | primitivemobs-1.2.3a.jar                              | None                                     |
       | LCHIJA | quickhomes           | 1.2.2                | QuickHomes-1.2.2.jar                                  | None                                     |
       | LCHIJA | quickleafdecay       | 1.2.4                | QuickLeafDecay-MC1.12.1-1.2.4.jar                     | None                                     |
       | LCHIJA | quickteleports       | 1.1.1                | quickteleports-1.12.2-1.1.1.jar                       | None                                     |
       | LCHIJA | rainboaks            | 1.0.4                | RainbowOaks-1.12-1.0.4.jar                            | None                                     |
       | LCHIJA | realdrops            | 1.2.14               | RealisticItemDrops-1.2.14.jar                         | None                                     |
       | LCHIJA | resourceloader       | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | corerm               | 1.3.3                | RikMuldsCore_1.3.3.jar                                | None                                     |
       | LCHIJA | soundfilters         | 0.12.1_for_1.12      | SoundFilters-0.12.1_for_1.12.jar                      | None                                     |
       | LCHIJA | spartanshields       | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                       | None                                     |
       | LCHIJA | srparasites          | 1.7.0                | SRParasites-1.12.2v1.7.0.jar                          | None                                     |
       | LCHIJA | stepup               | 1.0.2-mc1.10-1.12.2  | StepUp-1.0.2-mc1.10-1.12.jar                          | None                                     |
       | LCHIJA | streams              | 0.4.9                | Streams-1.12-0.4.9.jar                                | None                                     |
       | LCHIJA | camping              | 2.4.3                | TheCampingMod_2.4.3.jar                               | None                                     |
       | LCHIJA | tidychunk            | 1.0.0.0              | TidyChunk-1.12.2-1.0.0.0.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | timehud              | 7.3.1                | TimeHUD-1.12.2-7.3.1.jar                              | None                                     |
       | LCHIJA | tips                 | 1.0.9                | Tips-1.12.2-1.0.9.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | travelersdream       | 1.1                  | Traveler'sDream-Compact-1.12.2-v1.2.jar               | None                                     |
       | LCHIJA | vanillavistas        | 1.0                  | Vanilla_Vistas+1.1.jar                                | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-150           | VanillaFix-1.0.10-150.jar                             | None                                     |
       | LCHIJA | waterstrainer        | 3.3.0                | WaterStrainer-1.12-3.3.0.jar                          | None                                     |
       | LCHIJA | waystones            | 4.1.0                | Waystones_1.12.2-4.1.0.jar                            | None                                     |
       | LCHIJA | xaerominimap         | 21.8.2               | Xaeros_Minimap_21.8.2_Forge_1.12.jar                  | None                                     |
       | LCHIJA | xaeroworldmap        | 1.14.0               | XaerosWorldMap_1.14.0_Forge_1.12.jar                  | None                                     |
       | LCHIJA | zombiehorsespawn     | 2.7                  | zombiehorsespawn_1.12.2-2.7.jar                       | None                                     |
       | LCHIJA | betteranimalsplus    | 9.0.1                | betteranimalsplus-1.12.2-9.0.1.jar                    | None                                     |
       | LCHIJA | modwinder            | 1.1                  | Ladylib-2.3.jar                                       | None                                     |
       | LCHIJA | ladylib              | 2.3                  | Ladylib-2.3.jar                                       | None                                     |
       | LCHIJA | lumen                | 0.4.1                | lumen-Beta 0.4.2.jar                                  | None                                     |
       | LCHIJA | passableleaves       | 2.0.0                | PassableLeaves-1.12.2-2.0.0.jar                       | None                                     |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar           | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | quickspawns          | 1.0.0                | quickspawns-1.12.2-1.0.1.jar                          | None                                     |
       | LCHIJA | snowrealmagic        | 0.3.3                | SnowRealMagic-0.3.3.jar                               | None                                     |
       | LCHIJA | mysticallib          | 1.12.2-1.9.0         | mysticallib-1.12.2-1.9.0.jar                          | None                                     |
  Loaded coremods (and transformers): XaeroMinimapPlugin (Xaeros_Minimap_21.8.2_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      ParagliderLoadingPlugin (Paraglider-1.12.2-1.0.1.5.jar)
                                        com.tictim.paraglider.asm.TransformerModelBiped
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.14.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                      PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
                                        
                                      TickCentral (TickCentral-3.2.jar)
                                        com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer
                                        com.github.terminatornl.laggoggles.tickcentral.RenderManagerTransformer
                                        com.github.terminatornl.tickcentral.asm.BlockTransformer
                                        com.github.terminatornl.tickcentral.asm.ITickableTransformer
                                        com.github.terminatornl.tickcentral.asm.EntityTransformer
                                        com.github.terminatornl.tickcentral.asm.HubAPITransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      Pick Up Notifier (PickUpNotifier-v1.1.5-1.12.2.jar)
                                        com.fuzs.pickupnotifier.asm.ClassTransformer
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
                                        teamrtg.passableleaves.asm.PassableLeavesTransformer
                                      FutureMC (future-mc-1.12.2-0.2.6.1.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      EmojicordCorePlugin (Emojicord-1.12.2-1.1.1.39-universal.jar)
                                        net.teamfruit.emojicord.asm.EmojicordTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      HatedMobsLoadingPlugin (hatedmobs-1.5.0.jar)
                                        fr.uranoscopidae.hatedmobs.asm.HatedMobsTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.57_mc1.12.2.jar)
                                        
                                      FarseekCoreMod (Farseek-1.12-2.5.1.jar)
                                        farseek.core.FarseekClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 462.59' Renderer: 'GeForce RTX 2060/PCIe/SSE2'
  Patchouli open book context: n/a
  Suspected Mods: Hated Mobs (hatedmobs), Wumple Util Library (wumpleutil), LagGoggles (laggoggles)
```
